### ISSUE TITLE
NameError: global name 'settings' is not defined

### ISSUE THREAD

**Issue by MauricioAndrades** [lite3/Sublime-QuickGotoAnything#2]
Hi,

I'm receiving this error in Sublime Text 3 (3126) when loading QuickGoToAnything. I was wondering if you could help me debug this. I can provide any additional information you need.

I think the problem might be related to line 10 in QuickGoToAnythingSettings.py:
```
def plugin_loaded():
    settings.load_settings()
```

I don't see a settings plugin being imported or defined before this method is called.

```
plugins loaded
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 210, in on_api_ready
    m.plugin_loaded()
  File "QuickGotoAnythingSettings in /Users/Op/Library/Application Support/Sublime Text 3/Installed Packages/QuickGotoAnything.sublime-package", line 10, in plugin_loaded
NameError: global name 'settings' is not defined
```

**Comment by litefeel** [comment]
Hi @MauricioAndrades,
thanks for your feedback. 
You're right, I've fixed it.
